spring:
  profiles:
    active: dev  # 激活开发环境配置
  mvc:
    path match:
      matching-strategy: ant_path_matcher  # 关键配置：兼容 Swagger 2.x
  datasource:
    url: jdbc:mysql://localhost:3306/lixiaoyue?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root  # 你的MySQL用户名
    password: root  # 你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Redis相关配置
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0 #操作的是0号数据库(redis存在0-15号数据库（默认），在命令中使用select来切换)
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
springdoc:
  api-docs:
    path: /api-docs  # 接口文档JSON数据地址（默认即可）
  swagger-ui:
    path: /swagger-ui.html  # 可视化UI地址（默认即可）
    operationsSorter: method  # 接口排序方式（按请求方法排序）
# 服务器配置
server:
  port: 8080  # 项目端口
  servlet:
    context-path: /api  # 接口前缀（所有接口需加 /api）

# MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 可选，主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml  # Mapper.xml文件路径（若需）
  type-aliases-package: com.lixiaoyue.model.entity  # 实体类别名包
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志


lixiaoyue:
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com  # 根据实际创建的地域填写
    access-key-id: LTAI5t8LuuyuQGoJTJduwKr8      # 替换为你的AccessKey ID
    access-key-secret: hcxY3sPguZ1mEcVrTxMSKz4FJea4sd  # 替换为你的AccessKey Secret
    bucket-name: lixiaoyue         # 替换为你的Bucket名称